ktor:
  deployment:
    port: 8080
    host: "0.0.0.0"
  application:
    modules:
      - org.kinleoapple.ApplicationKt.module

ktorm:
  sqlite:
    url: "jdbc:sqlite:./memo.db"
    driver: "org.sqlite.JDBC"

memo:
  user:
    name: Kinleoapple
    password: 2460DOGCAT
  designer:
    name: Kinleoapple
    page: "https://github.com/KinLeoapple"