ktor:
  deployment:
    port: 8080
    host: "0.0.0.0"
  application:
    modules:
      - org.kinleoapple.ApplicationKt.module

ktorm:
  sqlite:
    url: "jdbc:sqlite:./memo.db"
    driver: "org.sqlite.JDBC"

# 这是一个过度方案，以后可能会考虑其他方式来配置用户信息
markdown:
  title: This is a test markdown
  desc: "A long time ago in a galaxy far,far away.
  Turmoil has enguifed the Galactic Republic.The taxation of trade routes to outlying star systems is in dispute.
  Hoping to resolve the matter with a blockade of deadly battleships,the greedy Trade Federation has stopped all shipping to the small planet of Naboo.
  While the Congress of the Republic endlessly debates this alarming chain of events,the Supreme Chancellor has secretly dispatched two Jedi Knights,the guardians of peace and justice in the galaxy,to settle the conflict."
  content: "<!-- https://github.com/kyechan99/capsule-render -->
<p align='center'>
  <img src='https://capsule-render.vercel.app/api?type=waving&color=timeGradient&height=300&&section=header&text=HELLO%20THERE!&fontSize=90&fontAlign=50&fontAlignY=30&desc=I%20am%20Kinleoapple!&descAlign=50&descSize=30&descAlignY=60&animation=twinkling' />
  </p>
  
  <!-- https://github.com/DenverCoder1/readme-typing-svg -->
  <p align='center'>
  <img src='https://readme-typing-svg.demolab.com?font=Orbitron&size=25&pause=1000&center=true&vCenter=true&random=false&width=600&lines=I+am+super+obsessed+with+programming!;Well+...+Maybe+not+...' />
  </p>
  
  <!-- https://github.com/anuraghazra/github-readme-stats -->
  <p align='center'>
  <img src='https://github-readme-stats.vercel.app/api?username=Kinleoapple&show_icons=true' />
  </p>
  
  <!-- https://github.com/badges/shields -->
  <p align='center'>
  <a href='https://github.com/KinLeoapple'><img src='https://img.shields.io/badge/GitHub-KinLeoapple-blue?logo=github' /></a>
  <a href='https://space.bilibili.com/77531961'><img src='https://img.shields.io/badge/哔哩哔哩-巷陌雨季-pink?logo=bilibili' /></a>
  <img src='https://img.shields.io/badge/QQ-996711203-green?logo=tencentqq' />
  <!-- https://github.com/antonkomarev/github-profile-views-counter -->
  <img src='https://komarev.com/ghpvc/?username=KinLeoapple&abbreviated=true&color=yellow' />
  </p>
  
  <!-- https://github.com/Ashutosh00710/github-readme-activity-graph -->
  <p align='center'>
  <img width='800' src='https://github-readme-activity-graph.vercel.app/graph?username=Kinleoapple&theme=github-compact&hide_border=true&area=true' />
  </p>
  
  <p align='center'>
  <img align='center' src='https://github-readme-stats.vercel.app/api/top-langs/?username=Kinleoapple&theme=transparent&hide_border=true&layout=donut-vertical&langs_count=6' />
  </p>
  
  <p align='center'>
  <a href='https://skillicons.dev'>
  <img src='https://skillicons.dev/icons?i=electron,flutter,go,html,java,js,kotlin,ktor,mongodb,py,react,vue,spring,sqlite,mysql' />
  </a>
  </p>
  
  <!-- https://github.com/kyechan99/capsule-render -->
  <p align='center'>
  <img src='https://capsule-render.vercel.app/api?type=waving&color=timeGradient&height=300&&section=footer&text=THE%20END!&fontSize=90&fontAlign=50&fontAlignY=70&desc=Enjoy%20your%20journey%20of%20coding!&descAlign=50&descSize=30&descAlignY=40&animation=twinkling' />
  </p>"