ktor:
  deployment:
    port: 8080
    host: "0.0.0.0"
  application:
    modules:
      - org.kinleoapple.ApplicationKt.module

ktorm:
  mysql:
    url: "jdbc:mysql://localhost:3306/memo"
    driver: "com.mysql.cj.jdbc.Driver"
    user: "root"
    password: "123456"

memo:
  user:
    name: Kinleoapple
    password: 2460DOGCAT
  designer:
    name: Kinleoapple
    page: "https://github.com/KinLeoapple"