ktor:
  deployment:
    port: 8080
    host: "0.0.0.0"
  application:
    modules:
      - org.kinleoapple.ApplicationKt.module

ktorm:
  sqlite:
    url: "jdbc:sqlite:./memo.db"
    driver: "org.sqlite.JDBC"

# 这是一个过度方案，以后可能会考虑其他方式来配置用户信息
markdown:
  title: This is a test markdown
  desc: "A long time ago in a galaxy far,far away.
  Turmoil has enguifed the Galactic Republic.The taxation of trade routes to outlying star systems is in dispute.
  Hoping to resolve the matter with a blockade of deadly battleships,the greedy Trade Federation has stopped all shipping to the small planet of Naboo.
  While the Congress of the Republic endlessly debates this alarming chain of events,the Supreme Chancellor has secretly dispatched two Jedi Knights,the guardians of peace and justice in the galaxy,to settle the conflict."
  content: "# 星球大战概览

**星球大战**（Star Wars）是美国导演乔治·卢卡斯创作的一部史诗式太空歌剧系列电影，自1977年首部电影《星球大战：新希望》公映以来，已经成为全球文化的一个重要组成部分，影响了几代人的电影制作和观影经验。

## 主要电影系列

### 原三部曲

1. **星球大战：新希望（Episode IV - A New Hope）** - 1977
   - 简介：故事讲述了卢克·天行者加入义军反抗邪恶的银河帝国，从而踏上了英雄之旅。
2. **星球大战：帝国反击战（Episode V - The Empire Strikes Back）** - 1980
   - 简介：帝国军对抗义军的战斗升级，卢克接受绝地训练，并揭开了自己惊人的身世之谜。
3. **星球大战：绝地归来（Episode VI - Return of the Jedi）** - 1983
   - 简介：卢克带领同伴最终摧毁了死星，帮助义军推翻了银河帝国，故事以绝地武士的胜利告终。

### 前传三部曲

1. **星球大战：魅影危机（Episode I - The Phantom Menace）** - 1999
   - 简介：揭示了达斯·维德年轻时的故事，以及他如何从阿纳金·天行者变成黑暗面的维德。
2. **星球大战：克隆人的进攻（Episode II - Attack of the Clones）** - 2002
   - 简介：克隆战争的爆发，揭示了银河共和国的内部危机和分裂。
3. **星球大战：西斯的复仇（Episode III - Revenge of the Sith）** - 2005
   - 简介：阿纳金的最终堕落和绝地武士团的覆灭，银河帝国的崛起。

### 续集三部曲

1. **星球大战：原力觉醒（Episode VII - The Force Awakens）** - 2015
   - 简介：原力新的觉醒者，雷（Rey）的出现，以及与抵抗组织共同对抗第一秩序。
2. **星球大战：最后的绝地武士（Episode VIII - The Last Jedi）** - 2017
   - 简介：雷的力量训练，以及对抗第一秩序的斗争加剧。
3. **星球大战：天行者崛起（Episode IX - The Rise of Skywalker）** - 2019
   - 简介：关于绝地与西斯之间的最终对决，以及银河系命运的最终决定。

## 重要角色

- **卢克·天行者（Luke Skywalker）**
  - 银河帝国时代末期的传奇英雄，绝地武士。
- **莱娅公主（Princess Leia）**
  - 阿尔德兰星的公主，义军的高级领导。
- **汉·索洛（Han Solo）**
  - 星际走私者，千年隼号的飞行员，莱娅公主的爱人。
- **达斯·维德（Darth Vader）/阿纳金·天行者（Anakin Skywalker）**
  - 从光明的绝地武士堕落为黑暗面的西斯领主。

## 主要影响

星球大战不仅仅是一部电影或电影系列，它是一个包括书籍、电视剧、电子游戏和各类商品的庞大娱乐帝国。这一系列影响了科幻电影的制作，定义了现代大制作电影的商业模式，并在全球范围内拥有庞大的粉丝群体。

星球大战以其复杂的人物、独特的世界观和深刻的主题，成为现代流行文化中不可或缺的一部分。它探讨了力量、责任、自由意志与命运的主题，让观众在享受视觉奇观的同时，也能引发深层次的思考。"